### ISSUE TITLE
dlxs config NameError

### ISSUE THREAD

**Issue by huangjqq** [mlibrary/rsvp#128]
When I run `process` with `-c dlxs` I'm running into a name error:
`[huangjq@tang processing]$ /l1/dev/moseshll/rsvp/bin/process -c dlxs kingfamily
Traceback (most recent call last):
	5: from /l1/dev/moseshll/rsvp/bin/process:58:in `<main>'
	4: from /l1/dev/moseshll/rsvp/bin/process:58:in `each'
	3: from /l1/dev/moseshll/rsvp/bin/process:65:in `block in <main>'
	2: from /l1/dev/moseshll/rsvp/bin/process:65:in `new'
	1: from /quod-dev/dev/moseshll/rsvp/lib/processor.rb:29:in `initialize'
/quod-dev/dev/moseshll/rsvp/lib/processor.rb:35:in `shipment_class': uninitialized constant DLXSShipment (NameError)`

**Comment by huangjqq** [comment]
This particular issue has been fixed, but now `process` is working, but only through the creation of the source directory with copies. No subsequent stages are running.

**Comment by moseshll** [comment]
Is `kingfamily` a shipment directory or the top level of a 3-directory object id? If `process` is run against the `xxxxxxxx/` directory where the object  is `xxxxxxxx/nnnn/nnn` then no processing will occur. It has to be run up a level at the shipment directory level. Try blowing away the status.json and source and try the enclosing directory.

**Comment by huangjqq** [comment]
Well, it was a top level of a 3-directory object id, but I tried it for the actual top level "shipment" directory one above that, and same problem. It doesn't even create a `status.json`, just appears to get stuck halfway through source creation part of preflight (though checking on it later shows that it does successfully copy everything)
