### ISSUE TITLE
ruby gem problems at /usr/local/

### ISSUE THREAD

**Issue by huangjqq** [mlibrary/rsvp#129]
After A&E moved the tool from `/l1/dev/moseshll` to `/usr/local/` the tool can't find gems when run from a tmux session. I'm not sure what's going on because it seems to work fine from just a regular session, i.e.
`[jvevans@tang 02_In_Process]$ /usr/local/rsvp/bin/process *
Could not find rake-13.0.3 in any of the sources
Run `bundle install` to install missing gems.`

Ryan tried running bundle install, but it didn't fix the problem.

**Comment by moseshll** [comment]
I was able to log in and from `~/` run `/usr/local/rsvp/bin/process -h` without errors.

**Comment by huangjqq** [comment]
It works for me if I'm just logged into the server, but not if I try it from a tmux session (even if I've refreshed my password recently, so the token isn't expired). I suppose it would be fine to just not run from a tmux session, since it should keep going even if the terminal session is closed (and I can modify the instructions to indicate that it needs to be run that way), but it used to work fine from the tmux session.
