### ISSUE TITLE
Keep processing error-less barcodes

### ISSUE THREAD

**Issue by moseshll** [mlibrary/rsvp#25]
Currently processing bails out when a stage reports one or more errors. We want to continue processing subsequent stages, skipping any barcodes that have errors. When we reprocess the shipment, the processor must construct something like an "agenda" that instructs stages to skip barcodes that have already succeeded.

An `Error` object that has a `nil` barcode should be interpreted as a general error and hard stop.

The `@error` arrays owned by the various stages should be sufficient to construct an agenda. `query.rb` should have an `agenda` command that lists the steps that will be taken in the next processing run. This would be a good time to revisit the processor's behavior when it is re-run on a shipment with errors. Does it automatically create a new agenda or does it refuse to do anything other than reiterate the error messages unless an `-r` flag is used? If the former, does it consult the `source` directory and metadata to automatically detect corrected files and run only on corrected barcodes? (This is probably the "smartest" behavior. I would propose that the "smart" agenda should be the default, perhaps with a flag to override the default in some way.)

**Comment by moseshll** [comment]
The `query.rb` command `status` could show a bar graph with the number of barcodes succeeding for each stage.

**Comment by huangjqq** [comment]
Shipment with problems:
/quod-prep/prep/d/dcu/huangjq/rsvp_testing/tiff_masters/problem_volumes/2020033_concierge

Fixes for those problems:
/quod-prep/prep/d/dcu/huangjq/rsvp_testing/tiff_masters/problem_volumes/2020033_fix
