### ISSUE TITLE
DLXS nested "barcode" directories

### ISSUE THREAD

**Issue by moseshll** [mlibrary/rsvp#54]
Expect DLXS shipments with pseudo-barcode directories of the volume/number serial for form `XXXX/YYY`. `Shipment` should be able to auto-identify this special case. We can use `XXXX/YYY` as the barcode when we need a string. May need to extend `Preflight` to look for bogus files inside `XXXX/` when this structure is identified. Also need to skip Luhn check.

`TestShipment` needs a DLXS subclass.

**Comment by huangjqq** [comment]
Sample DLXS shipment with nested directories:
/quod-prep/prep/d/dcu/huangjq/rsvp_testing/howew

**Comment by huangjqq** [comment]
The sample shipment is located at /quod-prep/prep/d/dcu/huangjq/rsvp_testing/sample_dlxs_shipment/ and contains images for a single sample DLXS volume in subdirectory howew/0001/001

**Comment by moseshll** [comment]
See /quod-dev/dev/roger/sandbox/scripts/tiff2jp2.pl for a possible way to generate TIFFs JHOVE will like.
